#!/bin/bash

NAME_SPACE="ev-odoo-dev-ubuntu"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "This will create a Postgres Docker container under namespace $NAME_SPACE"
read -p "Type 'ok' to continue: " user_input

if [[ "$user_input" == "ok" ]]; then
    docker-compose -f $SCRIPT_DIR/compose.yaml -p "$NAME_SPACE" up -d
else
    echo "Aborted"
    exit 1
fi
